dist: xenial
sudo: required
script:
- sudo apt-get install reprepro
- mkdir mesh-deb
- cd mesh-deb
- git clone https://github.com/tomeshnet/mesh-packages.git -b gh-pages .
- cd ..
- git clone https://github.com/tomeshnet/mesh-packages.git -b travis
- cp mesh-packages/README.md mesh-deb
- cp -r mesh-packages/repos mesh-deb/repos
- cd mesh-packages
- echo "-----BEGIN PGP PRIVATE KEY BLOCK-----" > gpg.key
- echo "$GPG" >> gpg.key
- echo "-----END PGP PRIVATE KEY BLOCK-----" >> gpg.key
- gpg --import mesh-packages/gpg.pub
- gpg --allow-secret-key-import --import gpg.key
- gpg --list-keys
- bash ./build-all.sh
- REPREPRO_BASE_DIR="../mesh-deb/repos/apt/debian" reprepro includedeb stretch *.deb
- cd ..
- find .
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: mesh-deb
  keep-history: false
  on:
    branch: travis
