dist: xenial
sudo: required
before_install:
  - openssl aes-256-cbc -K $encrypted_011506a0d8d1_key -iv $encrypted_011506a0d8d1_iv -in gpg.key.enc -out gpg.key -d
script:
- sudo apt-get -y install reprepro
- mkdir mesh-deb
- cd mesh-deb
- git clone https://github.com/tomeshnet/mesh-packages.git -b gh-pages .
- cd ..
- cp README.md mesh-deb
- cp -r repos mesh-deb/repos
- gpg --import gpg.pub
- gpg --allow-secret-key-import --import gpg.key
- gpg --list-keys
- bash ./build-all.sh
- REPREPRO_BASE_DIR="mesh-deb/repos/apt/debian" reprepro includedeb stretch packages/*.deb || true
- wget https://github.com/libthinkpad/apindex/archive/2.2.tar.gz
- tar xvf 2.2.tar.gz
- cd apindex-2.2
- cmake . -DCMAKE_INSTALL_PREFIX=/usr
- sudo make install
- cd ..
- apindex mesh-deb/repos
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: mesh-deb
  keep-history: false
  on:
    branch: travis
