dist: xenial
sudo: required
script:
- mkdir mesh-deb
- git clone https://github.com/tomeshnet/mesh-packages.git
- cp mesh-packages/README.md mesh-deb
- cd mesh-packages
- bash ./buildall.sh
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: mesh-deb
  keep-history: false
  on:
    branch: travis
