dist: xenial
sudo: required
script:
- apt-get -y install gpg
- mkdir mesh-deb
- git clone https://github.com/tomeshnet/mesh-packages.git
- cp mesh-packages/README.md mesh-deb
- cd mesh-packages
- git checkout travis
- echo "-----BEGIN PGP PRIVATE KEY BLOCK-----" > gpg.key
- echo $GPG >> gpg.key
- echo "-----END PGP PRIVATE KEY BLOCK-----" >> gpg.key
- gpg --import mesh-packages/gpg.pub
- gpg --allow-secret-key-import --import gpg.key
- gpg --list-keys
- bash ./build-all.sh
- ls -la
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: mesh-deb
  keep-history: false
  on:
    branch: travis
