dist: xenial
sudo: required
script:
- bash mkdir mesh-packages
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: mesh-packages
  keep-history: false
  fqdn: docs.tomesh.net
  on:
    branch: travis
